
#Mod integration config
[Integration]

	#Minecraft
	[Integration.minecraft]

		#Vanilla Minecraft
		[Integration.minecraft.minecraft]
			#Enabled Vanilla Minecraft integration. Default value is true
			enabled = true

	#Create
	[Integration.create]

		#Create Creative Crate
		[Integration.create.creative_crate]
			#Enabled Create Creative Crate integration. Default value is true
			enabled = true
			#Create Creative Crate storage priority. Items are inserted first into storages with higher priority. Default value is 0
			priority = 0

	#EnderStorage
	[Integration.enderstorage]

		#Ender Storage
		[Integration.enderstorage.ender_chest]
			#Enabled Ender Storage integration. Default value is true
			enabled = true
			#Ender Storage storage priority. Items are inserted first into storages with higher priority. Default value is 1
			priority = 1

	#Storage Drawers
	[Integration.storagedrawers]

		#standard drawers
		[Integration.storagedrawers.drawer]
			#Enabled standard drawers integration. Default value is true
			enabled = true
			#standard drawers storage priority. Items are inserted first into storages with higher priority. Default value is 10
			priority = 10

		#compacting drawers
		[Integration.storagedrawers.compacting_drawer]
			#Enabled compacting drawers integration. Default value is true
			enabled = true
			#compacting drawers storage priority. Items are inserted first into storages with higher priority. Default value is 10
			priority = 10

